name: Auto Create PR and Assign Reviewers

on:
  push:
    branches:
      - to_merge

  pull_request:
    types: [opened, reopened]

jobs:
  create-pull-request:
    if: github.event_name == 'push'
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for existing PR
      id: check_pr
      run: |
        PR_EXISTS=$(curl -s -X GET \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls \
          -d '{"state":"open","head":"${{ github.ref_name }}"}' | jq -r '. | length')
        echo "::set-output name=exists::$PR_EXISTS"

    - name: Create pull request
      if: steps.check_pr.outputs.exists == '0'
      uses: actions/http-client@v2
      with:
        url: https://api.github.com/repos/${{ github.repository }}/pulls
        method: POST
        headers: |
          Authorization: token ${{ secrets.PAT_TOKEN }}
          Accept: application/vnd.github.v3+json
        body: |
          {
            "title": "Automated PR for changes in ${{ github.ref_name }}",
            "body": "This PR was created automatically by the GitHub Actions workflow.",
            "head": "${{ github.ref_name }}",
            "base": "testing_branch"
          }

  add-reviewers:
    if: github.event_name == 'pull_request'
    runs-on: self-hosted

    steps:
    - name: Assign reviewers
      uses: actions/http-client@v2
      with:
        url: https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
        method: POST
        headers: |
          Authorization: token ${{ secrets.PAT_TOKEN }}
          Accept: application/vnd.github.v3+json
        body: |
          {
            "reviewers": ["maxmosecondgit"]
          }
